version: "0.2"
phases: 
  install:
    runtime-versions: 
      nodejs: 14
    commands:
      - echo "Installing AWS CLI"
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install --update
      - aws --version
      - npm install -g aws-cdk
  build:
    commands:
      - ls -l
      - sh ./scripts/build-account-factory.sh
